# Generated by Django 3.2.12 on 2022-03-08 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteuser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlogintime',
            name='logout_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
